package com.sample.ws.service.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-09T14:12:31.992+05:30
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://service.ws.sample.com/", name = "IStudentService")
@XmlSeeAlso({ObjectFactory.class})
public interface IStudentService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getStudent", targetNamespace = "http://service.ws.sample.com/", className = "com.sample.ws.service.client.GetStudent")
    @WebMethod
    @ResponseWrapper(localName = "getStudentResponse", targetNamespace = "http://service.ws.sample.com/", className = "com.sample.ws.service.client.GetStudentResponse")
    public com.sample.ws.service.client.Student getStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.sample.ws.service.client.Student arg0
    );
}
