package com.sample.ws.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2015-12-09T14:12:32.056+05:30
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "StudentServiceImplService", 
                  wsdlLocation = "http://localhost:8080/SpringMVC-1.0/services/StudentService?wsdl",
                  targetNamespace = "http://service.ws.sample.com/") 
public class StudentServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.sample.com/", "StudentServiceImplService");
    public final static QName StudentServiceImplPort = new QName("http://service.ws.sample.com/", "StudentServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SpringMVC-1.0/services/StudentService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StudentServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SpringMVC-1.0/services/StudentService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StudentServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StudentServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StudentServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public StudentServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StudentServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StudentServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IStudentService
     */
    @WebEndpoint(name = "StudentServiceImplPort")
    public IStudentService getStudentServiceImplPort() {
        return super.getPort(StudentServiceImplPort, IStudentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStudentService
     */
    @WebEndpoint(name = "StudentServiceImplPort")
    public IStudentService getStudentServiceImplPort(WebServiceFeature... features) {
        return super.getPort(StudentServiceImplPort, IStudentService.class, features);
    }

}
